services:
  - type: web
    name: varanasi
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      gunicorn varanasi.wsgi:application --log-file -

    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: varanasi.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

